version: '3'
services:
  api_platform:
    build:
      context: api_platform
      dockerfile: Dockerfile
    container_name: api_platform
    ports:
      - "8098:8089"
    volumes:
      - ./data/root/.djl.ai:/root/.djl.ai
      - /etc/localtime:/etc/localtime
    restart: always
